# Generated by Django 5.2 on 2025-04-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='source_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='url_to_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='symbol',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
