# Generated by Django 5.2 on 2025-04-12 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocktool', '0003_wishlist_delete_newsarticle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
