# Generated by Django 6.0 on 2025-12-10 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocktool', '0004_delete_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('bought_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_purchase', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
